### ISSUE TITLE
사용자로부터 입력받기

### ISSUE THREAD

**Issue by sujinjwa** [JhyunJ1/numguess#1]
### 요약
사용자로부터 이름과 정답을 입력 받는다.

### To Do LIst
- [x] 사용자로부터 이름 입력 받는다.
- [x] 입력 받은 이름을 활용하여 인사말을 출력한다.
- [x] 사용자로부터 정답을 입력 받는다.
- [x] 입력 받은 정답을 출력한다.
- [x] random 패키지 이용하여 랜덤한 값을 생성하여 정답값으로 설정한다.

**Comment by JhyunJ1** [comment]
Almost Done!
